// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_8_title.proto

package com.ourpalm.tank.message;

public final class ARMY_TITLE_MSG {
  private ARMY_TITLE_MSG() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code PROTO_TITLE.CMD_TYPE}
   */
  public enum CMD_TYPE
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>CMD_TYPE_TITLE = 8;</code>
     */
    CMD_TYPE_TITLE(0, 8),
    ;

    /**
     * <code>CMD_TYPE_TITLE = 8;</code>
     */
    public static final int CMD_TYPE_TITLE_VALUE = 8;


    public final int getNumber() { return value; }

    public static CMD_TYPE valueOf(int value) {
      switch (value) {
        case 8: return CMD_TYPE_TITLE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CMD_TYPE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CMD_TYPE>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CMD_TYPE>() {
            public CMD_TYPE findValueByNumber(int number) {
              return CMD_TYPE.valueOf(number);
            }
          };

    private final int value;

    private CMD_TYPE(int index, int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:PROTO_TITLE.CMD_TYPE)
  }

  /**
   * Protobuf enum {@code PROTO_TITLE.CMD_ID}
   */
  public enum CMD_ID
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>CTS_TITLE_INFO = 1;</code>
     *
     * <pre>
     *请求军衔信息(空命令)
     * </pre>
     */
    CTS_TITLE_INFO(0, 1),
    /**
     * <code>CTS_DRAW_DAY_REWARD = 2;</code>
     *
     * <pre>
     *领取赛季最高军衔每日奖励(空命令)
     * </pre>
     */
    CTS_DRAW_DAY_REWARD(1, 2),
    /**
     * <code>CTS_CURR_TITLE = 3;</code>
     *
     * <pre>
     *请求当前军衔(用于战场结束,显示军衔升级)(空命令)
     * </pre>
     */
    CTS_CURR_TITLE(2, 3),
    /**
     * <code>STC_TITLE_INFO = 4;</code>
     *
     * <pre>
     *返回军衔信息
     * </pre>
     */
    STC_TITLE_INFO(3, 4),
    /**
     * <code>STC_DRAW_DAY_REWARD = 5;</code>
     *
     * <pre>
     *领取赛季最高军衔每日奖励返回
     * </pre>
     */
    STC_DRAW_DAY_REWARD(4, 5),
    /**
     * <code>STC_CURR_TITLE = 6;</code>
     *
     * <pre>
     *请求当前军衔(用于战场结束,显示军衔升级)
     * </pre>
     */
    STC_CURR_TITLE(5, 6),
    ;

    /**
     * <code>CTS_TITLE_INFO = 1;</code>
     *
     * <pre>
     *请求军衔信息(空命令)
     * </pre>
     */
    public static final int CTS_TITLE_INFO_VALUE = 1;
    /**
     * <code>CTS_DRAW_DAY_REWARD = 2;</code>
     *
     * <pre>
     *领取赛季最高军衔每日奖励(空命令)
     * </pre>
     */
    public static final int CTS_DRAW_DAY_REWARD_VALUE = 2;
    /**
     * <code>CTS_CURR_TITLE = 3;</code>
     *
     * <pre>
     *请求当前军衔(用于战场结束,显示军衔升级)(空命令)
     * </pre>
     */
    public static final int CTS_CURR_TITLE_VALUE = 3;
    /**
     * <code>STC_TITLE_INFO = 4;</code>
     *
     * <pre>
     *返回军衔信息
     * </pre>
     */
    public static final int STC_TITLE_INFO_VALUE = 4;
    /**
     * <code>STC_DRAW_DAY_REWARD = 5;</code>
     *
     * <pre>
     *领取赛季最高军衔每日奖励返回
     * </pre>
     */
    public static final int STC_DRAW_DAY_REWARD_VALUE = 5;
    /**
     * <code>STC_CURR_TITLE = 6;</code>
     *
     * <pre>
     *请求当前军衔(用于战场结束,显示军衔升级)
     * </pre>
     */
    public static final int STC_CURR_TITLE_VALUE = 6;


    public final int getNumber() { return value; }

    public static CMD_ID valueOf(int value) {
      switch (value) {
        case 1: return CTS_TITLE_INFO;
        case 2: return CTS_DRAW_DAY_REWARD;
        case 3: return CTS_CURR_TITLE;
        case 4: return STC_TITLE_INFO;
        case 5: return STC_DRAW_DAY_REWARD;
        case 6: return STC_CURR_TITLE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CMD_ID>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CMD_ID>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CMD_ID>() {
            public CMD_ID findValueByNumber(int number) {
              return CMD_ID.valueOf(number);
            }
          };

    private final int value;

    private CMD_ID(int index, int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:PROTO_TITLE.CMD_ID)
  }

  public interface STC_TITLE_INFO_MSGOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // required uint32 currTitleId = 1;
    /**
     * <code>required uint32 currTitleId = 1;</code>
     *
     * <pre>
     *当前军衔ID
     * </pre>
     */
    boolean hasCurrTitleId();
    /**
     * <code>required uint32 currTitleId = 1;</code>
     *
     * <pre>
     *当前军衔ID
     * </pre>
     */
    int getCurrTitleId();

    // required uint32 seasonMaxTitleId = 2;
    /**
     * <code>required uint32 seasonMaxTitleId = 2;</code>
     *
     * <pre>
     *本赛季最高军衔ID
     * </pre>
     */
    boolean hasSeasonMaxTitleId();
    /**
     * <code>required uint32 seasonMaxTitleId = 2;</code>
     *
     * <pre>
     *本赛季最高军衔ID
     * </pre>
     */
    int getSeasonMaxTitleId();

    // required bool hadDrawDay = 3;
    /**
     * <code>required bool hadDrawDay = 3;</code>
     *
     * <pre>
     *是否领取每日奖励(true 已领取)
     * </pre>
     */
    boolean hasHadDrawDay();
    /**
     * <code>required bool hadDrawDay = 3;</code>
     *
     * <pre>
     *是否领取每日奖励(true 已领取)
     * </pre>
     */
    boolean getHadDrawDay();

    // required uint32 iron = 4;
    /**
     * <code>required uint32 iron = 4;</code>
     *
     * <pre>
     *银币
     * </pre>
     */
    boolean hasIron();
    /**
     * <code>required uint32 iron = 4;</code>
     *
     * <pre>
     *银币
     * </pre>
     */
    int getIron();

    // required uint32 gold = 5;
    /**
     * <code>required uint32 gold = 5;</code>
     *
     * <pre>
     *金币
     * </pre>
     */
    boolean hasGold();
    /**
     * <code>required uint32 gold = 5;</code>
     *
     * <pre>
     *金币
     * </pre>
     */
    int getGold();

    // required uint32 honor = 6;
    /**
     * <code>required uint32 honor = 6;</code>
     *
     * <pre>
     *荣誉
     * </pre>
     */
    boolean hasHonor();
    /**
     * <code>required uint32 honor = 6;</code>
     *
     * <pre>
     *荣誉
     * </pre>
     */
    int getHonor();

    // required string context = 7;
    /**
     * <code>required string context = 7;</code>
     *
     * <pre>
     *赛季结束说明
     * </pre>
     */
    boolean hasContext();
    /**
     * <code>required string context = 7;</code>
     *
     * <pre>
     *赛季结束说明
     * </pre>
     */
    java.lang.String getContext();
    /**
     * <code>required string context = 7;</code>
     *
     * <pre>
     *赛季结束说明
     * </pre>
     */
    com.google.protobuf.ByteString
        getContextBytes();

    // required uint32 score = 8;
    /**
     * <code>required uint32 score = 8;</code>
     *
     * <pre>
     *军衔积分
     * </pre>
     */
    boolean hasScore();
    /**
     * <code>required uint32 score = 8;</code>
     *
     * <pre>
     *军衔积分
     * </pre>
     */
    int getScore();

    // required uint32 maxScore = 9;
    /**
     * <code>required uint32 maxScore = 9;</code>
     *
     * <pre>
     *本军衔最大积分
     * </pre>
     */
    boolean hasMaxScore();
    /**
     * <code>required uint32 maxScore = 9;</code>
     *
     * <pre>
     *本军衔最大积分
     * </pre>
     */
    int getMaxScore();
  }
  /**
   * Protobuf type {@code PROTO_TITLE.STC_TITLE_INFO_MSG}
   *
   * <pre>
   *返回军衔信息
   * </pre>
   */
  public static final class STC_TITLE_INFO_MSG extends
      com.google.protobuf.GeneratedMessageLite
      implements STC_TITLE_INFO_MSGOrBuilder {
    // Use STC_TITLE_INFO_MSG.newBuilder() to construct.
    private STC_TITLE_INFO_MSG(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private STC_TITLE_INFO_MSG(boolean noInit) {}

    private static final STC_TITLE_INFO_MSG defaultInstance;
    public static STC_TITLE_INFO_MSG getDefaultInstance() {
      return defaultInstance;
    }

    public STC_TITLE_INFO_MSG getDefaultInstanceForType() {
      return defaultInstance;
    }

    private STC_TITLE_INFO_MSG(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              currTitleId_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              seasonMaxTitleId_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              hadDrawDay_ = input.readBool();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              iron_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              gold_ = input.readUInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              honor_ = input.readUInt32();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              context_ = input.readBytes();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              score_ = input.readUInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              maxScore_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<STC_TITLE_INFO_MSG> PARSER =
        new com.google.protobuf.AbstractParser<STC_TITLE_INFO_MSG>() {
      public STC_TITLE_INFO_MSG parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new STC_TITLE_INFO_MSG(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<STC_TITLE_INFO_MSG> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint32 currTitleId = 1;
    public static final int CURRTITLEID_FIELD_NUMBER = 1;
    private int currTitleId_;
    /**
     * <code>required uint32 currTitleId = 1;</code>
     *
     * <pre>
     *当前军衔ID
     * </pre>
     */
    public boolean hasCurrTitleId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 currTitleId = 1;</code>
     *
     * <pre>
     *当前军衔ID
     * </pre>
     */
    public int getCurrTitleId() {
      return currTitleId_;
    }

    // required uint32 seasonMaxTitleId = 2;
    public static final int SEASONMAXTITLEID_FIELD_NUMBER = 2;
    private int seasonMaxTitleId_;
    /**
     * <code>required uint32 seasonMaxTitleId = 2;</code>
     *
     * <pre>
     *本赛季最高军衔ID
     * </pre>
     */
    public boolean hasSeasonMaxTitleId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 seasonMaxTitleId = 2;</code>
     *
     * <pre>
     *本赛季最高军衔ID
     * </pre>
     */
    public int getSeasonMaxTitleId() {
      return seasonMaxTitleId_;
    }

    // required bool hadDrawDay = 3;
    public static final int HADDRAWDAY_FIELD_NUMBER = 3;
    private boolean hadDrawDay_;
    /**
     * <code>required bool hadDrawDay = 3;</code>
     *
     * <pre>
     *是否领取每日奖励(true 已领取)
     * </pre>
     */
    public boolean hasHadDrawDay() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bool hadDrawDay = 3;</code>
     *
     * <pre>
     *是否领取每日奖励(true 已领取)
     * </pre>
     */
    public boolean getHadDrawDay() {
      return hadDrawDay_;
    }

    // required uint32 iron = 4;
    public static final int IRON_FIELD_NUMBER = 4;
    private int iron_;
    /**
     * <code>required uint32 iron = 4;</code>
     *
     * <pre>
     *银币
     * </pre>
     */
    public boolean hasIron() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required uint32 iron = 4;</code>
     *
     * <pre>
     *银币
     * </pre>
     */
    public int getIron() {
      return iron_;
    }

    // required uint32 gold = 5;
    public static final int GOLD_FIELD_NUMBER = 5;
    private int gold_;
    /**
     * <code>required uint32 gold = 5;</code>
     *
     * <pre>
     *金币
     * </pre>
     */
    public boolean hasGold() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required uint32 gold = 5;</code>
     *
     * <pre>
     *金币
     * </pre>
     */
    public int getGold() {
      return gold_;
    }

    // required uint32 honor = 6;
    public static final int HONOR_FIELD_NUMBER = 6;
    private int honor_;
    /**
     * <code>required uint32 honor = 6;</code>
     *
     * <pre>
     *荣誉
     * </pre>
     */
    public boolean hasHonor() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required uint32 honor = 6;</code>
     *
     * <pre>
     *荣誉
     * </pre>
     */
    public int getHonor() {
      return honor_;
    }

    // required string context = 7;
    public static final int CONTEXT_FIELD_NUMBER = 7;
    private java.lang.Object context_;
    /**
     * <code>required string context = 7;</code>
     *
     * <pre>
     *赛季结束说明
     * </pre>
     */
    public boolean hasContext() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required string context = 7;</code>
     *
     * <pre>
     *赛季结束说明
     * </pre>
     */
    public java.lang.String getContext() {
      java.lang.Object ref = context_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          context_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string context = 7;</code>
     *
     * <pre>
     *赛季结束说明
     * </pre>
     */
    public com.google.protobuf.ByteString
        getContextBytes() {
      java.lang.Object ref = context_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        context_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required uint32 score = 8;
    public static final int SCORE_FIELD_NUMBER = 8;
    private int score_;
    /**
     * <code>required uint32 score = 8;</code>
     *
     * <pre>
     *军衔积分
     * </pre>
     */
    public boolean hasScore() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required uint32 score = 8;</code>
     *
     * <pre>
     *军衔积分
     * </pre>
     */
    public int getScore() {
      return score_;
    }

    // required uint32 maxScore = 9;
    public static final int MAXSCORE_FIELD_NUMBER = 9;
    private int maxScore_;
    /**
     * <code>required uint32 maxScore = 9;</code>
     *
     * <pre>
     *本军衔最大积分
     * </pre>
     */
    public boolean hasMaxScore() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required uint32 maxScore = 9;</code>
     *
     * <pre>
     *本军衔最大积分
     * </pre>
     */
    public int getMaxScore() {
      return maxScore_;
    }

    private void initFields() {
      currTitleId_ = 0;
      seasonMaxTitleId_ = 0;
      hadDrawDay_ = false;
      iron_ = 0;
      gold_ = 0;
      honor_ = 0;
      context_ = "";
      score_ = 0;
      maxScore_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCurrTitleId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSeasonMaxTitleId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHadDrawDay()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIron()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGold()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHonor()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContext()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasScore()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMaxScore()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, currTitleId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, seasonMaxTitleId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, hadDrawDay_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, iron_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, gold_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt32(6, honor_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getContextBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeUInt32(8, score_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeUInt32(9, maxScore_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, currTitleId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, seasonMaxTitleId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, hadDrawDay_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, iron_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, gold_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, honor_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getContextBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(8, score_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(9, maxScore_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_TITLE_INFO_MSG parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_TITLE_INFO_MSG parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_TITLE_INFO_MSG parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_TITLE_INFO_MSG parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_TITLE_INFO_MSG parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_TITLE_INFO_MSG parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_TITLE_INFO_MSG parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_TITLE_INFO_MSG parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_TITLE_INFO_MSG parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_TITLE_INFO_MSG parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_TITLE_INFO_MSG prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code PROTO_TITLE.STC_TITLE_INFO_MSG}
     *
     * <pre>
     *返回军衔信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_TITLE_INFO_MSG, Builder>
        implements com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_TITLE_INFO_MSGOrBuilder {
      // Construct using com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_TITLE_INFO_MSG.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        currTitleId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        seasonMaxTitleId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        hadDrawDay_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        iron_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        gold_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        honor_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        context_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        score_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        maxScore_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_TITLE_INFO_MSG getDefaultInstanceForType() {
        return com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_TITLE_INFO_MSG.getDefaultInstance();
      }

      public com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_TITLE_INFO_MSG build() {
        com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_TITLE_INFO_MSG result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_TITLE_INFO_MSG buildPartial() {
        com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_TITLE_INFO_MSG result = new com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_TITLE_INFO_MSG(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.currTitleId_ = currTitleId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.seasonMaxTitleId_ = seasonMaxTitleId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.hadDrawDay_ = hadDrawDay_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.iron_ = iron_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.gold_ = gold_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.honor_ = honor_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.context_ = context_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.score_ = score_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.maxScore_ = maxScore_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_TITLE_INFO_MSG other) {
        if (other == com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_TITLE_INFO_MSG.getDefaultInstance()) return this;
        if (other.hasCurrTitleId()) {
          setCurrTitleId(other.getCurrTitleId());
        }
        if (other.hasSeasonMaxTitleId()) {
          setSeasonMaxTitleId(other.getSeasonMaxTitleId());
        }
        if (other.hasHadDrawDay()) {
          setHadDrawDay(other.getHadDrawDay());
        }
        if (other.hasIron()) {
          setIron(other.getIron());
        }
        if (other.hasGold()) {
          setGold(other.getGold());
        }
        if (other.hasHonor()) {
          setHonor(other.getHonor());
        }
        if (other.hasContext()) {
          bitField0_ |= 0x00000040;
          context_ = other.context_;
          
        }
        if (other.hasScore()) {
          setScore(other.getScore());
        }
        if (other.hasMaxScore()) {
          setMaxScore(other.getMaxScore());
        }
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCurrTitleId()) {
          
          return false;
        }
        if (!hasSeasonMaxTitleId()) {
          
          return false;
        }
        if (!hasHadDrawDay()) {
          
          return false;
        }
        if (!hasIron()) {
          
          return false;
        }
        if (!hasGold()) {
          
          return false;
        }
        if (!hasHonor()) {
          
          return false;
        }
        if (!hasContext()) {
          
          return false;
        }
        if (!hasScore()) {
          
          return false;
        }
        if (!hasMaxScore()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_TITLE_INFO_MSG parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_TITLE_INFO_MSG) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint32 currTitleId = 1;
      private int currTitleId_ ;
      /**
       * <code>required uint32 currTitleId = 1;</code>
       *
       * <pre>
       *当前军衔ID
       * </pre>
       */
      public boolean hasCurrTitleId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 currTitleId = 1;</code>
       *
       * <pre>
       *当前军衔ID
       * </pre>
       */
      public int getCurrTitleId() {
        return currTitleId_;
      }
      /**
       * <code>required uint32 currTitleId = 1;</code>
       *
       * <pre>
       *当前军衔ID
       * </pre>
       */
      public Builder setCurrTitleId(int value) {
        bitField0_ |= 0x00000001;
        currTitleId_ = value;
        
        return this;
      }
      /**
       * <code>required uint32 currTitleId = 1;</code>
       *
       * <pre>
       *当前军衔ID
       * </pre>
       */
      public Builder clearCurrTitleId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        currTitleId_ = 0;
        
        return this;
      }

      // required uint32 seasonMaxTitleId = 2;
      private int seasonMaxTitleId_ ;
      /**
       * <code>required uint32 seasonMaxTitleId = 2;</code>
       *
       * <pre>
       *本赛季最高军衔ID
       * </pre>
       */
      public boolean hasSeasonMaxTitleId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 seasonMaxTitleId = 2;</code>
       *
       * <pre>
       *本赛季最高军衔ID
       * </pre>
       */
      public int getSeasonMaxTitleId() {
        return seasonMaxTitleId_;
      }
      /**
       * <code>required uint32 seasonMaxTitleId = 2;</code>
       *
       * <pre>
       *本赛季最高军衔ID
       * </pre>
       */
      public Builder setSeasonMaxTitleId(int value) {
        bitField0_ |= 0x00000002;
        seasonMaxTitleId_ = value;
        
        return this;
      }
      /**
       * <code>required uint32 seasonMaxTitleId = 2;</code>
       *
       * <pre>
       *本赛季最高军衔ID
       * </pre>
       */
      public Builder clearSeasonMaxTitleId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        seasonMaxTitleId_ = 0;
        
        return this;
      }

      // required bool hadDrawDay = 3;
      private boolean hadDrawDay_ ;
      /**
       * <code>required bool hadDrawDay = 3;</code>
       *
       * <pre>
       *是否领取每日奖励(true 已领取)
       * </pre>
       */
      public boolean hasHadDrawDay() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bool hadDrawDay = 3;</code>
       *
       * <pre>
       *是否领取每日奖励(true 已领取)
       * </pre>
       */
      public boolean getHadDrawDay() {
        return hadDrawDay_;
      }
      /**
       * <code>required bool hadDrawDay = 3;</code>
       *
       * <pre>
       *是否领取每日奖励(true 已领取)
       * </pre>
       */
      public Builder setHadDrawDay(boolean value) {
        bitField0_ |= 0x00000004;
        hadDrawDay_ = value;
        
        return this;
      }
      /**
       * <code>required bool hadDrawDay = 3;</code>
       *
       * <pre>
       *是否领取每日奖励(true 已领取)
       * </pre>
       */
      public Builder clearHadDrawDay() {
        bitField0_ = (bitField0_ & ~0x00000004);
        hadDrawDay_ = false;
        
        return this;
      }

      // required uint32 iron = 4;
      private int iron_ ;
      /**
       * <code>required uint32 iron = 4;</code>
       *
       * <pre>
       *银币
       * </pre>
       */
      public boolean hasIron() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required uint32 iron = 4;</code>
       *
       * <pre>
       *银币
       * </pre>
       */
      public int getIron() {
        return iron_;
      }
      /**
       * <code>required uint32 iron = 4;</code>
       *
       * <pre>
       *银币
       * </pre>
       */
      public Builder setIron(int value) {
        bitField0_ |= 0x00000008;
        iron_ = value;
        
        return this;
      }
      /**
       * <code>required uint32 iron = 4;</code>
       *
       * <pre>
       *银币
       * </pre>
       */
      public Builder clearIron() {
        bitField0_ = (bitField0_ & ~0x00000008);
        iron_ = 0;
        
        return this;
      }

      // required uint32 gold = 5;
      private int gold_ ;
      /**
       * <code>required uint32 gold = 5;</code>
       *
       * <pre>
       *金币
       * </pre>
       */
      public boolean hasGold() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required uint32 gold = 5;</code>
       *
       * <pre>
       *金币
       * </pre>
       */
      public int getGold() {
        return gold_;
      }
      /**
       * <code>required uint32 gold = 5;</code>
       *
       * <pre>
       *金币
       * </pre>
       */
      public Builder setGold(int value) {
        bitField0_ |= 0x00000010;
        gold_ = value;
        
        return this;
      }
      /**
       * <code>required uint32 gold = 5;</code>
       *
       * <pre>
       *金币
       * </pre>
       */
      public Builder clearGold() {
        bitField0_ = (bitField0_ & ~0x00000010);
        gold_ = 0;
        
        return this;
      }

      // required uint32 honor = 6;
      private int honor_ ;
      /**
       * <code>required uint32 honor = 6;</code>
       *
       * <pre>
       *荣誉
       * </pre>
       */
      public boolean hasHonor() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required uint32 honor = 6;</code>
       *
       * <pre>
       *荣誉
       * </pre>
       */
      public int getHonor() {
        return honor_;
      }
      /**
       * <code>required uint32 honor = 6;</code>
       *
       * <pre>
       *荣誉
       * </pre>
       */
      public Builder setHonor(int value) {
        bitField0_ |= 0x00000020;
        honor_ = value;
        
        return this;
      }
      /**
       * <code>required uint32 honor = 6;</code>
       *
       * <pre>
       *荣誉
       * </pre>
       */
      public Builder clearHonor() {
        bitField0_ = (bitField0_ & ~0x00000020);
        honor_ = 0;
        
        return this;
      }

      // required string context = 7;
      private java.lang.Object context_ = "";
      /**
       * <code>required string context = 7;</code>
       *
       * <pre>
       *赛季结束说明
       * </pre>
       */
      public boolean hasContext() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string context = 7;</code>
       *
       * <pre>
       *赛季结束说明
       * </pre>
       */
      public java.lang.String getContext() {
        java.lang.Object ref = context_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          context_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string context = 7;</code>
       *
       * <pre>
       *赛季结束说明
       * </pre>
       */
      public com.google.protobuf.ByteString
          getContextBytes() {
        java.lang.Object ref = context_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          context_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string context = 7;</code>
       *
       * <pre>
       *赛季结束说明
       * </pre>
       */
      public Builder setContext(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        context_ = value;
        
        return this;
      }
      /**
       * <code>required string context = 7;</code>
       *
       * <pre>
       *赛季结束说明
       * </pre>
       */
      public Builder clearContext() {
        bitField0_ = (bitField0_ & ~0x00000040);
        context_ = getDefaultInstance().getContext();
        
        return this;
      }
      /**
       * <code>required string context = 7;</code>
       *
       * <pre>
       *赛季结束说明
       * </pre>
       */
      public Builder setContextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        context_ = value;
        
        return this;
      }

      // required uint32 score = 8;
      private int score_ ;
      /**
       * <code>required uint32 score = 8;</code>
       *
       * <pre>
       *军衔积分
       * </pre>
       */
      public boolean hasScore() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required uint32 score = 8;</code>
       *
       * <pre>
       *军衔积分
       * </pre>
       */
      public int getScore() {
        return score_;
      }
      /**
       * <code>required uint32 score = 8;</code>
       *
       * <pre>
       *军衔积分
       * </pre>
       */
      public Builder setScore(int value) {
        bitField0_ |= 0x00000080;
        score_ = value;
        
        return this;
      }
      /**
       * <code>required uint32 score = 8;</code>
       *
       * <pre>
       *军衔积分
       * </pre>
       */
      public Builder clearScore() {
        bitField0_ = (bitField0_ & ~0x00000080);
        score_ = 0;
        
        return this;
      }

      // required uint32 maxScore = 9;
      private int maxScore_ ;
      /**
       * <code>required uint32 maxScore = 9;</code>
       *
       * <pre>
       *本军衔最大积分
       * </pre>
       */
      public boolean hasMaxScore() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required uint32 maxScore = 9;</code>
       *
       * <pre>
       *本军衔最大积分
       * </pre>
       */
      public int getMaxScore() {
        return maxScore_;
      }
      /**
       * <code>required uint32 maxScore = 9;</code>
       *
       * <pre>
       *本军衔最大积分
       * </pre>
       */
      public Builder setMaxScore(int value) {
        bitField0_ |= 0x00000100;
        maxScore_ = value;
        
        return this;
      }
      /**
       * <code>required uint32 maxScore = 9;</code>
       *
       * <pre>
       *本军衔最大积分
       * </pre>
       */
      public Builder clearMaxScore() {
        bitField0_ = (bitField0_ & ~0x00000100);
        maxScore_ = 0;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PROTO_TITLE.STC_TITLE_INFO_MSG)
    }

    static {
      defaultInstance = new STC_TITLE_INFO_MSG(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PROTO_TITLE.STC_TITLE_INFO_MSG)
  }

  public interface STC_DRAW_DAY_REWARD_MSGOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // required bool success = 1;
    /**
     * <code>required bool success = 1;</code>
     *
     * <pre>
     *是否成功
     * </pre>
     */
    boolean hasSuccess();
    /**
     * <code>required bool success = 1;</code>
     *
     * <pre>
     *是否成功
     * </pre>
     */
    boolean getSuccess();

    // required string info = 2;
    /**
     * <code>required string info = 2;</code>
     *
     * <pre>
     *提示信息
     * </pre>
     */
    boolean hasInfo();
    /**
     * <code>required string info = 2;</code>
     *
     * <pre>
     *提示信息
     * </pre>
     */
    java.lang.String getInfo();
    /**
     * <code>required string info = 2;</code>
     *
     * <pre>
     *提示信息
     * </pre>
     */
    com.google.protobuf.ByteString
        getInfoBytes();

    // required uint32 iron = 3;
    /**
     * <code>required uint32 iron = 3;</code>
     *
     * <pre>
     *银币
     * </pre>
     */
    boolean hasIron();
    /**
     * <code>required uint32 iron = 3;</code>
     *
     * <pre>
     *银币
     * </pre>
     */
    int getIron();

    // required uint32 gold = 4;
    /**
     * <code>required uint32 gold = 4;</code>
     *
     * <pre>
     *金币
     * </pre>
     */
    boolean hasGold();
    /**
     * <code>required uint32 gold = 4;</code>
     *
     * <pre>
     *金币
     * </pre>
     */
    int getGold();

    // required uint32 honor = 5;
    /**
     * <code>required uint32 honor = 5;</code>
     *
     * <pre>
     *荣誉
     * </pre>
     */
    boolean hasHonor();
    /**
     * <code>required uint32 honor = 5;</code>
     *
     * <pre>
     *荣誉
     * </pre>
     */
    int getHonor();
  }
  /**
   * Protobuf type {@code PROTO_TITLE.STC_DRAW_DAY_REWARD_MSG}
   *
   * <pre>
   *赛季每日奖励返回
   * </pre>
   */
  public static final class STC_DRAW_DAY_REWARD_MSG extends
      com.google.protobuf.GeneratedMessageLite
      implements STC_DRAW_DAY_REWARD_MSGOrBuilder {
    // Use STC_DRAW_DAY_REWARD_MSG.newBuilder() to construct.
    private STC_DRAW_DAY_REWARD_MSG(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private STC_DRAW_DAY_REWARD_MSG(boolean noInit) {}

    private static final STC_DRAW_DAY_REWARD_MSG defaultInstance;
    public static STC_DRAW_DAY_REWARD_MSG getDefaultInstance() {
      return defaultInstance;
    }

    public STC_DRAW_DAY_REWARD_MSG getDefaultInstanceForType() {
      return defaultInstance;
    }

    private STC_DRAW_DAY_REWARD_MSG(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              success_ = input.readBool();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              info_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              iron_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              gold_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              honor_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<STC_DRAW_DAY_REWARD_MSG> PARSER =
        new com.google.protobuf.AbstractParser<STC_DRAW_DAY_REWARD_MSG>() {
      public STC_DRAW_DAY_REWARD_MSG parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new STC_DRAW_DAY_REWARD_MSG(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<STC_DRAW_DAY_REWARD_MSG> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bool success = 1;
    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>required bool success = 1;</code>
     *
     * <pre>
     *是否成功
     * </pre>
     */
    public boolean hasSuccess() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool success = 1;</code>
     *
     * <pre>
     *是否成功
     * </pre>
     */
    public boolean getSuccess() {
      return success_;
    }

    // required string info = 2;
    public static final int INFO_FIELD_NUMBER = 2;
    private java.lang.Object info_;
    /**
     * <code>required string info = 2;</code>
     *
     * <pre>
     *提示信息
     * </pre>
     */
    public boolean hasInfo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string info = 2;</code>
     *
     * <pre>
     *提示信息
     * </pre>
     */
    public java.lang.String getInfo() {
      java.lang.Object ref = info_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          info_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string info = 2;</code>
     *
     * <pre>
     *提示信息
     * </pre>
     */
    public com.google.protobuf.ByteString
        getInfoBytes() {
      java.lang.Object ref = info_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        info_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required uint32 iron = 3;
    public static final int IRON_FIELD_NUMBER = 3;
    private int iron_;
    /**
     * <code>required uint32 iron = 3;</code>
     *
     * <pre>
     *银币
     * </pre>
     */
    public boolean hasIron() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint32 iron = 3;</code>
     *
     * <pre>
     *银币
     * </pre>
     */
    public int getIron() {
      return iron_;
    }

    // required uint32 gold = 4;
    public static final int GOLD_FIELD_NUMBER = 4;
    private int gold_;
    /**
     * <code>required uint32 gold = 4;</code>
     *
     * <pre>
     *金币
     * </pre>
     */
    public boolean hasGold() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required uint32 gold = 4;</code>
     *
     * <pre>
     *金币
     * </pre>
     */
    public int getGold() {
      return gold_;
    }

    // required uint32 honor = 5;
    public static final int HONOR_FIELD_NUMBER = 5;
    private int honor_;
    /**
     * <code>required uint32 honor = 5;</code>
     *
     * <pre>
     *荣誉
     * </pre>
     */
    public boolean hasHonor() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required uint32 honor = 5;</code>
     *
     * <pre>
     *荣誉
     * </pre>
     */
    public int getHonor() {
      return honor_;
    }

    private void initFields() {
      success_ = false;
      info_ = "";
      iron_ = 0;
      gold_ = 0;
      honor_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSuccess()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasInfo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIron()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGold()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHonor()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, success_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getInfoBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, iron_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, gold_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, honor_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getInfoBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, iron_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, gold_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, honor_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_DRAW_DAY_REWARD_MSG parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_DRAW_DAY_REWARD_MSG parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_DRAW_DAY_REWARD_MSG parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_DRAW_DAY_REWARD_MSG parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_DRAW_DAY_REWARD_MSG parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_DRAW_DAY_REWARD_MSG parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_DRAW_DAY_REWARD_MSG parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_DRAW_DAY_REWARD_MSG parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_DRAW_DAY_REWARD_MSG parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_DRAW_DAY_REWARD_MSG parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_DRAW_DAY_REWARD_MSG prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code PROTO_TITLE.STC_DRAW_DAY_REWARD_MSG}
     *
     * <pre>
     *赛季每日奖励返回
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_DRAW_DAY_REWARD_MSG, Builder>
        implements com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_DRAW_DAY_REWARD_MSGOrBuilder {
      // Construct using com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_DRAW_DAY_REWARD_MSG.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        success_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        info_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        iron_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        gold_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        honor_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_DRAW_DAY_REWARD_MSG getDefaultInstanceForType() {
        return com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_DRAW_DAY_REWARD_MSG.getDefaultInstance();
      }

      public com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_DRAW_DAY_REWARD_MSG build() {
        com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_DRAW_DAY_REWARD_MSG result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_DRAW_DAY_REWARD_MSG buildPartial() {
        com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_DRAW_DAY_REWARD_MSG result = new com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_DRAW_DAY_REWARD_MSG(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.success_ = success_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.info_ = info_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.iron_ = iron_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.gold_ = gold_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.honor_ = honor_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_DRAW_DAY_REWARD_MSG other) {
        if (other == com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_DRAW_DAY_REWARD_MSG.getDefaultInstance()) return this;
        if (other.hasSuccess()) {
          setSuccess(other.getSuccess());
        }
        if (other.hasInfo()) {
          bitField0_ |= 0x00000002;
          info_ = other.info_;
          
        }
        if (other.hasIron()) {
          setIron(other.getIron());
        }
        if (other.hasGold()) {
          setGold(other.getGold());
        }
        if (other.hasHonor()) {
          setHonor(other.getHonor());
        }
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSuccess()) {
          
          return false;
        }
        if (!hasInfo()) {
          
          return false;
        }
        if (!hasIron()) {
          
          return false;
        }
        if (!hasGold()) {
          
          return false;
        }
        if (!hasHonor()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_DRAW_DAY_REWARD_MSG parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_DRAW_DAY_REWARD_MSG) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bool success = 1;
      private boolean success_ ;
      /**
       * <code>required bool success = 1;</code>
       *
       * <pre>
       *是否成功
       * </pre>
       */
      public boolean hasSuccess() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool success = 1;</code>
       *
       * <pre>
       *是否成功
       * </pre>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>required bool success = 1;</code>
       *
       * <pre>
       *是否成功
       * </pre>
       */
      public Builder setSuccess(boolean value) {
        bitField0_ |= 0x00000001;
        success_ = value;
        
        return this;
      }
      /**
       * <code>required bool success = 1;</code>
       *
       * <pre>
       *是否成功
       * </pre>
       */
      public Builder clearSuccess() {
        bitField0_ = (bitField0_ & ~0x00000001);
        success_ = false;
        
        return this;
      }

      // required string info = 2;
      private java.lang.Object info_ = "";
      /**
       * <code>required string info = 2;</code>
       *
       * <pre>
       *提示信息
       * </pre>
       */
      public boolean hasInfo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string info = 2;</code>
       *
       * <pre>
       *提示信息
       * </pre>
       */
      public java.lang.String getInfo() {
        java.lang.Object ref = info_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          info_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string info = 2;</code>
       *
       * <pre>
       *提示信息
       * </pre>
       */
      public com.google.protobuf.ByteString
          getInfoBytes() {
        java.lang.Object ref = info_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          info_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string info = 2;</code>
       *
       * <pre>
       *提示信息
       * </pre>
       */
      public Builder setInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        info_ = value;
        
        return this;
      }
      /**
       * <code>required string info = 2;</code>
       *
       * <pre>
       *提示信息
       * </pre>
       */
      public Builder clearInfo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        info_ = getDefaultInstance().getInfo();
        
        return this;
      }
      /**
       * <code>required string info = 2;</code>
       *
       * <pre>
       *提示信息
       * </pre>
       */
      public Builder setInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        info_ = value;
        
        return this;
      }

      // required uint32 iron = 3;
      private int iron_ ;
      /**
       * <code>required uint32 iron = 3;</code>
       *
       * <pre>
       *银币
       * </pre>
       */
      public boolean hasIron() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint32 iron = 3;</code>
       *
       * <pre>
       *银币
       * </pre>
       */
      public int getIron() {
        return iron_;
      }
      /**
       * <code>required uint32 iron = 3;</code>
       *
       * <pre>
       *银币
       * </pre>
       */
      public Builder setIron(int value) {
        bitField0_ |= 0x00000004;
        iron_ = value;
        
        return this;
      }
      /**
       * <code>required uint32 iron = 3;</code>
       *
       * <pre>
       *银币
       * </pre>
       */
      public Builder clearIron() {
        bitField0_ = (bitField0_ & ~0x00000004);
        iron_ = 0;
        
        return this;
      }

      // required uint32 gold = 4;
      private int gold_ ;
      /**
       * <code>required uint32 gold = 4;</code>
       *
       * <pre>
       *金币
       * </pre>
       */
      public boolean hasGold() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required uint32 gold = 4;</code>
       *
       * <pre>
       *金币
       * </pre>
       */
      public int getGold() {
        return gold_;
      }
      /**
       * <code>required uint32 gold = 4;</code>
       *
       * <pre>
       *金币
       * </pre>
       */
      public Builder setGold(int value) {
        bitField0_ |= 0x00000008;
        gold_ = value;
        
        return this;
      }
      /**
       * <code>required uint32 gold = 4;</code>
       *
       * <pre>
       *金币
       * </pre>
       */
      public Builder clearGold() {
        bitField0_ = (bitField0_ & ~0x00000008);
        gold_ = 0;
        
        return this;
      }

      // required uint32 honor = 5;
      private int honor_ ;
      /**
       * <code>required uint32 honor = 5;</code>
       *
       * <pre>
       *荣誉
       * </pre>
       */
      public boolean hasHonor() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required uint32 honor = 5;</code>
       *
       * <pre>
       *荣誉
       * </pre>
       */
      public int getHonor() {
        return honor_;
      }
      /**
       * <code>required uint32 honor = 5;</code>
       *
       * <pre>
       *荣誉
       * </pre>
       */
      public Builder setHonor(int value) {
        bitField0_ |= 0x00000010;
        honor_ = value;
        
        return this;
      }
      /**
       * <code>required uint32 honor = 5;</code>
       *
       * <pre>
       *荣誉
       * </pre>
       */
      public Builder clearHonor() {
        bitField0_ = (bitField0_ & ~0x00000010);
        honor_ = 0;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PROTO_TITLE.STC_DRAW_DAY_REWARD_MSG)
    }

    static {
      defaultInstance = new STC_DRAW_DAY_REWARD_MSG(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PROTO_TITLE.STC_DRAW_DAY_REWARD_MSG)
  }

  public interface STC_CURR_TITLE_MSGOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // required uint32 titleId = 1;
    /**
     * <code>required uint32 titleId = 1;</code>
     *
     * <pre>
     *当前军衔ID
     * </pre>
     */
    boolean hasTitleId();
    /**
     * <code>required uint32 titleId = 1;</code>
     *
     * <pre>
     *当前军衔ID
     * </pre>
     */
    int getTitleId();

    // required bool isMax = 2;
    /**
     * <code>required bool isMax = 2;</code>
     *
     * <pre>
     *是否为本赛季最高军衔
     * </pre>
     */
    boolean hasIsMax();
    /**
     * <code>required bool isMax = 2;</code>
     *
     * <pre>
     *是否为本赛季最高军衔
     * </pre>
     */
    boolean getIsMax();
  }
  /**
   * Protobuf type {@code PROTO_TITLE.STC_CURR_TITLE_MSG}
   */
  public static final class STC_CURR_TITLE_MSG extends
      com.google.protobuf.GeneratedMessageLite
      implements STC_CURR_TITLE_MSGOrBuilder {
    // Use STC_CURR_TITLE_MSG.newBuilder() to construct.
    private STC_CURR_TITLE_MSG(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private STC_CURR_TITLE_MSG(boolean noInit) {}

    private static final STC_CURR_TITLE_MSG defaultInstance;
    public static STC_CURR_TITLE_MSG getDefaultInstance() {
      return defaultInstance;
    }

    public STC_CURR_TITLE_MSG getDefaultInstanceForType() {
      return defaultInstance;
    }

    private STC_CURR_TITLE_MSG(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              titleId_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              isMax_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<STC_CURR_TITLE_MSG> PARSER =
        new com.google.protobuf.AbstractParser<STC_CURR_TITLE_MSG>() {
      public STC_CURR_TITLE_MSG parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new STC_CURR_TITLE_MSG(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<STC_CURR_TITLE_MSG> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint32 titleId = 1;
    public static final int TITLEID_FIELD_NUMBER = 1;
    private int titleId_;
    /**
     * <code>required uint32 titleId = 1;</code>
     *
     * <pre>
     *当前军衔ID
     * </pre>
     */
    public boolean hasTitleId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 titleId = 1;</code>
     *
     * <pre>
     *当前军衔ID
     * </pre>
     */
    public int getTitleId() {
      return titleId_;
    }

    // required bool isMax = 2;
    public static final int ISMAX_FIELD_NUMBER = 2;
    private boolean isMax_;
    /**
     * <code>required bool isMax = 2;</code>
     *
     * <pre>
     *是否为本赛季最高军衔
     * </pre>
     */
    public boolean hasIsMax() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bool isMax = 2;</code>
     *
     * <pre>
     *是否为本赛季最高军衔
     * </pre>
     */
    public boolean getIsMax() {
      return isMax_;
    }

    private void initFields() {
      titleId_ = 0;
      isMax_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTitleId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsMax()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, titleId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, isMax_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, titleId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isMax_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_CURR_TITLE_MSG parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_CURR_TITLE_MSG parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_CURR_TITLE_MSG parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_CURR_TITLE_MSG parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_CURR_TITLE_MSG parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_CURR_TITLE_MSG parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_CURR_TITLE_MSG parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_CURR_TITLE_MSG parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_CURR_TITLE_MSG parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_CURR_TITLE_MSG parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_CURR_TITLE_MSG prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code PROTO_TITLE.STC_CURR_TITLE_MSG}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_CURR_TITLE_MSG, Builder>
        implements com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_CURR_TITLE_MSGOrBuilder {
      // Construct using com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_CURR_TITLE_MSG.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        titleId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        isMax_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_CURR_TITLE_MSG getDefaultInstanceForType() {
        return com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_CURR_TITLE_MSG.getDefaultInstance();
      }

      public com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_CURR_TITLE_MSG build() {
        com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_CURR_TITLE_MSG result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_CURR_TITLE_MSG buildPartial() {
        com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_CURR_TITLE_MSG result = new com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_CURR_TITLE_MSG(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.titleId_ = titleId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isMax_ = isMax_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_CURR_TITLE_MSG other) {
        if (other == com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_CURR_TITLE_MSG.getDefaultInstance()) return this;
        if (other.hasTitleId()) {
          setTitleId(other.getTitleId());
        }
        if (other.hasIsMax()) {
          setIsMax(other.getIsMax());
        }
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTitleId()) {
          
          return false;
        }
        if (!hasIsMax()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_CURR_TITLE_MSG parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ourpalm.tank.message.ARMY_TITLE_MSG.STC_CURR_TITLE_MSG) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint32 titleId = 1;
      private int titleId_ ;
      /**
       * <code>required uint32 titleId = 1;</code>
       *
       * <pre>
       *当前军衔ID
       * </pre>
       */
      public boolean hasTitleId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 titleId = 1;</code>
       *
       * <pre>
       *当前军衔ID
       * </pre>
       */
      public int getTitleId() {
        return titleId_;
      }
      /**
       * <code>required uint32 titleId = 1;</code>
       *
       * <pre>
       *当前军衔ID
       * </pre>
       */
      public Builder setTitleId(int value) {
        bitField0_ |= 0x00000001;
        titleId_ = value;
        
        return this;
      }
      /**
       * <code>required uint32 titleId = 1;</code>
       *
       * <pre>
       *当前军衔ID
       * </pre>
       */
      public Builder clearTitleId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        titleId_ = 0;
        
        return this;
      }

      // required bool isMax = 2;
      private boolean isMax_ ;
      /**
       * <code>required bool isMax = 2;</code>
       *
       * <pre>
       *是否为本赛季最高军衔
       * </pre>
       */
      public boolean hasIsMax() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bool isMax = 2;</code>
       *
       * <pre>
       *是否为本赛季最高军衔
       * </pre>
       */
      public boolean getIsMax() {
        return isMax_;
      }
      /**
       * <code>required bool isMax = 2;</code>
       *
       * <pre>
       *是否为本赛季最高军衔
       * </pre>
       */
      public Builder setIsMax(boolean value) {
        bitField0_ |= 0x00000002;
        isMax_ = value;
        
        return this;
      }
      /**
       * <code>required bool isMax = 2;</code>
       *
       * <pre>
       *是否为本赛季最高军衔
       * </pre>
       */
      public Builder clearIsMax() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isMax_ = false;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PROTO_TITLE.STC_CURR_TITLE_MSG)
    }

    static {
      defaultInstance = new STC_CURR_TITLE_MSG(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PROTO_TITLE.STC_CURR_TITLE_MSG)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
