package com.ourpalm.tank.constant;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;
import com.ourpalm.tank.dao.entity.AccountpayEntity;

/**
 * Generated by JFinal, do not modify this file.
 * 
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("accountpay_entity", "id", AccountpayEntity.class);
	}
}
