package com.ourpalm.tank.dao.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAccountpayEntity<M extends BaseAccountpayEntity<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setAccountID(java.lang.String accountID) {
		set("accountID", accountID);
	}

	public java.lang.String getAccountID() {
		return get("accountID");
	}

	public void setRoleId(java.lang.Integer roleId) {
		set("roleId", roleId);
	}

	public java.lang.Integer getRoleId() {
		return get("roleId");
	}

	public void setToken(java.lang.String token) {
		set("token", token);
	}

	public java.lang.String getToken() {
		return get("token");
	}

	public void setChannelId(java.lang.String channelId) {
		set("channelId", channelId);
	}

	public java.lang.String getChannelId() {
		return get("channelId");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setCreateTime(java.lang.Long createTime) {
		set("createTime", createTime);
	}

	public java.lang.Long getCreateTime() {
		return get("createTime");
	}

	public void setCallBackTime(java.lang.Long callBackTime) {
		set("callBackTime", callBackTime);
	}

	public java.lang.Long getCallBackTime() {
		return get("callBackTime");
	}

	public void setFinishTime(java.lang.Long finishTime) {
		set("finishTime", finishTime);
	}

	public java.lang.Long getFinishTime() {
		return get("finishTime");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}

	public java.lang.Integer getState() {
		return get("state");
	}

	public void setItemId(java.lang.Integer itemId) {
		set("itemId", itemId);
	}

	public java.lang.Integer getItemId() {
		return get("itemId");
	}

	public void setActualPrice(java.lang.Integer actualPrice) {
		set("actualPrice", actualPrice);
	}

	public java.lang.Integer getActualPrice() {
		return get("actualPrice");
	}

	public void setPubacctPayAmt(java.lang.Integer pubacctPayAmt) {
		set("pubacctPayAmt", pubacctPayAmt);
	}

	public java.lang.Integer getPubacctPayAmt() {
		return get("pubacctPayAmt");
	}

	public void setRebatePrice(java.lang.Integer rebatePrice) {
		set("rebatePrice", rebatePrice);
	}

	public java.lang.Integer getRebatePrice() {
		return get("rebatePrice");
	}

	public void setRebateGoodsId(java.lang.Integer rebateGoodsId) {
		set("rebateGoodsId", rebateGoodsId);
	}

	public java.lang.Integer getRebateGoodsId() {
		return get("rebateGoodsId");
	}

	public void setBillno(java.lang.String billno) {
		set("billno", billno);
	}

	public java.lang.String getBillno() {
		return get("billno");
	}

}
