package com.ourpalm.tank.dao.entity;

import com.ourpalm.tank.dao.base.BaseAccountpayEntity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AccountpayEntity extends BaseAccountpayEntity<AccountpayEntity> {
	public static final AccountpayEntity dao = new AccountpayEntity();
}
